// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIanXSKW0rMQLu1P6fBmPXT3p6_3X9pE',
    appId: '1:402637192110:web:1be89284761611c99d663f',
    messagingSenderId: '402637192110',
    projectId: 'alpha-bank-e918c',
    authDomain: 'alpha-bank-e918c.firebaseapp.com',
    storageBucket: 'alpha-bank-e918c.firebasestorage.app',
    measurementId: 'G-QMH5DM09HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RF_9kwP9jrNLcX4WsGaIh0Yb-51hWbg',
    appId: '1:402637192110:android:61bfe191d57364e39d663f',
    messagingSenderId: '402637192110',
    projectId: 'alpha-bank-e918c',
    storageBucket: 'alpha-bank-e918c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rQAGbS38fBMDtoxk6HcOtvbTRmc6uHM',
    appId: '1:402637192110:ios:d29da795bd5389249d663f',
    messagingSenderId: '402637192110',
    projectId: 'alpha-bank-e918c',
    storageBucket: 'alpha-bank-e918c.firebasestorage.app',
    iosBundleId: 'com.example.alphaWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6rQAGbS38fBMDtoxk6HcOtvbTRmc6uHM',
    appId: '1:402637192110:ios:d29da795bd5389249d663f',
    messagingSenderId: '402637192110',
    projectId: 'alpha-bank-e918c',
    storageBucket: 'alpha-bank-e918c.firebasestorage.app',
    iosBundleId: 'com.example.alphaWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABIanXSKW0rMQLu1P6fBmPXT3p6_3X9pE',
    appId: '1:402637192110:web:1be89284761611c99d663f',
    messagingSenderId: '402637192110',
    projectId: 'alpha-bank-e918c',
    authDomain: 'alpha-bank-e918c.firebaseapp.com',
    storageBucket: 'alpha-bank-e918c.firebasestorage.app',
    measurementId: 'G-QMH5DM09HW',
  );
}
