import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <- GENERATED BY FLUTTERFIRE
import 'theme/alpha_theme.dart';
import 'screens/splash_screen.dart';
import 'screens/welcome_screen.dart';
import 'screens/registration_screen.dart';
import 'screens/create_password_screen.dart';
import 'screens/support_screen.dart';

import 'screens/forgot_password_screen.dart';
import 'screens/create_pin_screen.dart';
import 'screens/login_screen.dart';
import 'screens/alpha_dashboard.dart';
import 'providers/auth_provider.dart';
import 'providers/wallet_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const AlphaWalletApp());
}

class AlphaWalletApp extends StatelessWidget {
  const AlphaWalletApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => WalletProvider()),
      ],
      child: MaterialApp(
        title: 'Alpha Wallet',
        theme: AlphaTheme.lightTheme,
        initialRoute: '/splash',
        debugShowCheckedModeBanner: false,
        routes: {
          '/splash': (context) => const SplashScreen(),
          '/welcome': (context) => const WelcomeScreen(),
          '/registration': (context) => const RegistrationScreen(),
          '/create-password': (context) => const CreatePasswordScreen(),
          '/create-pin': (context) => const CreatePinScreen(),
          '/login': (context) => const LoginScreen(),
          '/dashboard': (context) => const AlphaDashboard(),
          '/forgot-password': (context) => const ForgotPasswordScreen(),
          '/support': (context) => const SupportScreen(),
        },
      ),
    );
  }
}
